Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -64,7 +64,10 @@ jobs:
 
       - name: Run Molecule tests
         run: |
-          molecule test
+          molecule test || (
+           echo "Molecule test failed. Debugging logs:";
+           cat molecule/default/logs/*;
+            )
         env:
           ANSIBLE_FORCE_COLOR: "1"
           ANSIBLE_VERBOSITY: "2"
